#pragma once

class Player {
public:
	Player(int i_x, int i_y, float i_vel);
    void givePath(int* pathX, int* pathY, int pathLenght);
    void move();
private:
	int row;
	int col;
	float velocity;


    //Getters and Setters (autogenerated)
public:
    inline int getRow() { return row; }
    inline void setRow(int row) { this->row = row; }

    inline int getCol() { return col; }
    inline void setY(int col) { this->col = col; }

    inline float getVelocity() { return velocity; }
    inline void setVelocity(float velocity) { this->velocity = velocity; }

};
