#pragma once

class Player {
public:
	Player(int i_col, int i_row, int i_width, int i_height, float i_vel);
    void givePath(int* pathX, int* pathY, int pathLenght);
    void move();
private:
	int row;
	int col;
	float velocity;
    
    int drawWidth;
    int drawHeight;

    //Getters and Setters (autogenerated)
public:
    inline int getRow() { return row; }
    inline void setRow(int row) { this->row = row; }

    inline int getCol() { return col; }
    inline void setY(int col) { this->col = col; }

    inline float getVelocity() { return velocity; }
    inline void setVelocity(float velocity) { this->velocity = velocity; }

    inline int getDrawWidth() { return drawWidth; }
    inline void setDrawWidth(int drawWidth) { this->drawWidth = drawWidth; }

    inline int getDrawHeight() { return drawHeight; }
    inline void setDrawHeight(int drawHeight) { this->drawHeight = drawHeight; }

};
